"use client";

import { usePathname, useRouter } from "next/navigation";
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import { MusicButton } from "@/components/music/music-button";
import { MediaClient } from "@/lib/media/media-client";
import type { LocalMedia, MediaParticipant, RemoteMedia } from "@/lib/media/types";
import type { VoiceSettings } from "@/lib/voice-settings";

type PersistentCallSession = { href?: string; id: string; kind: "friend" | "group"; title: string; subtitle?: string; participant: { id: string; name: string; email: string }; signalingRoomId: string; roomId: string; endUrl?: string; statusUrl?: string; voiceSettings?: VoiceSettings };
type Context = { activeCall: PersistentCallSession | null; endCall: () => void; endedCallIds: ReadonlySet<string>; poppedOut: boolean; setPoppedOut: (value: boolean) => void; startCall: (session: PersistentCallSession) => void; media: MediaClient | null; snapshot: ReturnType<MediaClient["snapshot"]> | null };
const CallContext = createContext<Context | null>(null);
const endedKey = "val:ended-media-sessions";
const readEnded = () => { try { return new Set<string>(JSON.parse(sessionStorage.getItem(endedKey) ?? "[]")); } catch { return new Set<string>(); } };

export function PersistentCallProvider({ children }: { children: React.ReactNode }) {
  const [activeCall, setActiveCall] = useState<PersistentCallSession | null>(null); const [endedCallIds, setEnded] = useState<ReadonlySet<string>>(() => typeof window === "undefined" ? new Set() : readEnded()); const [poppedOut, setPoppedOut] = useState(false); const [snapshot, setSnapshot] = useState<ReturnType<MediaClient["snapshot"]> | null>(null); const [media, setMedia] = useState<MediaClient | null>(null); const clientRef = useRef<MediaClient | null>(null); const pathname = usePathname(); const router = useRouter();
  const remember = useCallback((id: string) => setEnded((current) => { const next = new Set(current); next.add(id); sessionStorage.setItem(endedKey, JSON.stringify([...next].slice(-50))); return next; }), []);
  const endCall = useCallback(() => { const session = activeCall; if (!session) return; void clientRef.current?.leave(); clientRef.current = null; setMedia(null); if (session.endUrl) void fetch(session.endUrl, { method: "POST" }); remember(session.id); setActiveCall(null); setPoppedOut(false); if (session.kind === "friend" && pathname === session.href) router.replace("/dashboard/messages"); }, [activeCall, pathname, remember, router]);
  const startCall = useCallback((session: PersistentCallSession) => { void clientRef.current?.leave(); const client = new MediaClient(); clientRef.current = client; setMedia(client); const unsubscribe = client.subscribe(() => setSnapshot(client.snapshot())); setActiveCall(session); setPoppedOut(false); setEnded((current) => { const next = new Set(current); next.delete(session.id); return next; }); void client.connect({ participant: session.participant, signalingRoomId: session.signalingRoomId }).then(async () => { const settings = session.voiceSettings; if (!settings?.joinMuted) await client.start("mic", { autoGainControl: settings?.autoGainControl, deviceId: settings?.inputDeviceId ? { ideal: settings.inputDeviceId } : undefined, echoCancellation: settings?.echoCancellation, noiseSuppression: settings?.noiseSuppression }); }).catch((error) => { console.error("Media connection failed", error); void client.leave(); if (clientRef.current === client) { clientRef.current = null; setMedia(null); setActiveCall(null); } }).finally(unsubscribe); }, []);
  useEffect(() => () => { void clientRef.current?.leave(); }, []);
  useEffect(() => { if (!activeCall?.statusUrl) return; const timer = window.setInterval(async () => { const response = await fetch(activeCall.statusUrl!).catch(() => null); const data = await response?.json().catch(() => null) as { status?: string } | null; if (["DECLINED", "MISSED", "ENDED"].includes(data?.status ?? "")) endCall(); }, 3000); return () => clearInterval(timer); }, [activeCall?.statusUrl, endCall]);
  const value = useMemo(() => ({ activeCall, endCall, endedCallIds, poppedOut, setPoppedOut, startCall, media, snapshot }), [activeCall, endCall, endedCallIds, media, poppedOut, snapshot, startCall]); return <CallContext.Provider value={value}>{children}</CallContext.Provider>;
}
export function usePersistentCall() { const value = useContext(CallContext); if (!value) throw new Error("usePersistentCall must be used within PersistentCallProvider."); return value; }
export function useOptionalPersistentCall() { return useContext(CallContext); }

export function PersistentCallSurface({ sessionId }: { sessionId: string }) { const call = usePersistentCall(); if (!call.activeCall || call.activeCall.id !== sessionId) return null; if (call.poppedOut) return <section className="grid min-h-0 flex-1 place-items-center px-5 py-8"><div className="app-panel p-6 text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#FF5F25]">Call popped out</p><button className="app-button-primary mt-4 h-11 rounded-lg px-4" onClick={() => call.setPoppedOut(false)} type="button">Return to call</button></div></section>; return <section className="flex min-h-0 flex-1 flex-col overflow-hidden bg-[#050705] p-2 sm:p-4"><header className="mb-2 flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-[#0b0f0b] px-3 py-2"><div><p className="text-[11px] font-semibold uppercase tracking-[.2em] text-[#FF5F25]">{call.activeCall.kind === "friend" ? "Friend call" : "Voice room"}</p><h2 className="text-base font-semibold text-white">{call.activeCall.title}</h2></div><button className="app-button-secondary h-10 rounded-lg px-3 text-xs" onClick={() => call.setPoppedOut(true)} type="button">Pop out</button></header><div className="min-h-0 flex-1 overflow-auto rounded-lg border border-white/10 bg-black p-3"><MediaGrid local={call.snapshot?.local ?? []} remote={call.snapshot?.remote ?? []} /></div><MediaControls /></section>; }
function MediaGrid({ local, remote }: { local: LocalMedia[]; remote: RemoteMedia[] }) { const localVideo = local.filter((item) => item.kind === "video"); const remoteVideo = remote.filter((item) => item.kind === "video"); return <><div className="sr-only">{remote.filter((item) => item.kind === "audio").map((item) => <RemoteAudioElement key={item.consumerId} item={item} />)}</div>{localVideo.length || remoteVideo.length ? <div className="grid gap-3 lg:grid-cols-2">{localVideo.map((item) => <LocalMediaElement key={`${item.source}:${item.track.id}`} item={item} />)}{remoteVideo.map((item) => <RemoteVideoElement key={item.consumerId} item={item} />)}</div> : <div className="grid h-full min-h-52 place-items-center text-center text-sm text-slate-400">Waiting for participants. Remote voice plays automatically when someone joins.</div>}</>; }
function RemoteAudioElement({ item }: { item: RemoteMedia }) { const audioRef = useRef<HTMLAudioElement>(null); useEffect(() => { if (!audioRef.current) return; audioRef.current.srcObject = new MediaStream([item.track]); void audioRef.current.play().catch(() => undefined); }, [item]); return <audio autoPlay ref={audioRef} />; }
function LocalMediaElement({ item }: { item: LocalMedia }) { return <VideoMediaElement item={item} label={`You · ${item.source === "screen" ? "Screen share" : "Camera"}`} muted />; }
function RemoteVideoElement({ item }: { item: RemoteMedia }) { return <VideoMediaElement item={item} label={item.source === "screen" ? "Screen share" : "Camera"} />; }
function VideoMediaElement({ item, label, muted = false }: { item: LocalMedia | RemoteMedia; label: string; muted?: boolean }) { const videoRef = useRef<HTMLVideoElement>(null); useEffect(() => { if (!videoRef.current) return; videoRef.current.srcObject = new MediaStream([item.track]); void videoRef.current.play().catch(() => undefined); }, [item]); return <div className="relative overflow-hidden rounded-lg border border-white/10 bg-[#0b1020]"><video autoPlay className="aspect-video h-full w-full object-contain" muted={muted} playsInline ref={videoRef} /><span className="absolute bottom-2 left-2 rounded bg-black/70 px-2 py-1 text-xs text-white">{label}</span></div>; }
function MediaControls() { const { activeCall, endCall, media, snapshot } = usePersistentCall(); const [busy, setBusy] = useState(false); if (!activeCall || !media) return null; const run = (action: () => Promise<unknown>) => { setBusy(true); void action().catch(console.error).finally(() => setBusy(false)); }; return <footer className="mt-2 flex flex-wrap justify-center gap-2 rounded-lg border border-white/10 bg-[#0b0f0b] p-2"><button className="app-button-secondary h-10 rounded-lg px-3 text-xs" disabled={busy} onClick={() => run(() => snapshot?.micMuted ? media.setMicMuted(false) : media.setMicMuted(true))} type="button">{snapshot?.micMuted ? "Unmute" : "Mute"}</button>{activeCall.kind === "group" ? <button className="app-button-secondary h-10 rounded-lg px-3 text-xs" disabled={busy} onClick={() => run(() => snapshot?.cameraOn ? media.stop("camera") : media.start("camera", true))} type="button">{snapshot?.cameraOn ? "Stop camera" : "Camera"}</button> : null}<button className="app-button-secondary h-10 rounded-lg px-3 text-xs" disabled={busy} onClick={() => run(() => snapshot?.screenOn ? media.stop("screen") : media.start("screen", true))} type="button">{snapshot?.screenOn ? "Stop sharing" : "Share screen"}</button>{activeCall.kind === "group" ? <MusicButton /> : null}<button className="app-button-danger h-10 rounded-lg px-3 text-xs" onClick={endCall} type="button">Leave</button></footer>; }

export function ParticipantVoiceControlsPanel({ onClose, participant }: { onClose: () => void; participant: MediaParticipant }) { return <div className="absolute right-0 top-full z-50 mt-2 w-64 rounded-lg border border-white/10 bg-[#080b10] p-3 shadow-2xl"><div className="flex justify-between gap-2"><p className="truncate text-sm font-semibold text-white">{participant.metadata?.name || participant.userId}</p><button className="text-slate-400" onClick={onClose} type="button">Close</button></div><p className="mt-2 text-xs text-slate-400">Local participant controls are available from the call surface.</p></div>; }
