import { closePeer, createPeer } from "../mediasoup/peerManager.mjs";

const reply = async (callback, action) => { try { callback({ ok: true, ...(await action()) }); } catch (error) { console.error("media signaling error", error); callback({ error: error instanceof Error ? error.message : "Media signaling failed." }); } };
const transportData = (transport) => ({ id: transport.id, iceParameters: transport.iceParameters, iceCandidates: transport.iceCandidates, dtlsParameters: transport.dtlsParameters });
export function registerSocketHandlers(io, socket, roomManager, transportConfig) {
  let room; let peer;
  socket.on("join-room", ({ roomId }, callback) => reply(callback, async () => { if (roomId !== socket.data.media.roomId) throw new Error("Room authorization failed."); if (room) closePeer(room, peer); room = await roomManager.getOrCreate(roomId); peer = createPeer(socket); room.peers.set(socket.id, peer); socket.join(roomId); socket.to(roomId).emit("peer-joined", { userId: peer.userId, metadata: peer.metadata }); return { rtpCapabilities: room.router.rtpCapabilities, producers: [...room.peers.values()].filter((item) => item !== peer).flatMap((item) => [...item.producers.values()].map((producer) => ({ producerId: producer.id, userId: item.userId, source: producer.appData.source, kind: producer.kind }))) }; }));
  socket.on("create-transport", ({ direction }, callback) => reply(callback, async () => { if (!room || !peer || !["send", "recv"].includes(direction)) throw new Error("Join a media room first."); const transport = await room.router.createWebRtcTransport(transportConfig); transport.appData.direction = direction; peer.transports.set(transport.id, transport); transport.on("close", () => peer.transports.delete(transport.id)); return transportData(transport); }));
  socket.on("connect-transport", ({ transportId, dtlsParameters }, callback) => reply(callback, async () => { const transport = peer?.transports.get(transportId); if (!transport) throw new Error("Transport not found."); await transport.connect({ dtlsParameters }); return {}; }));
  socket.on("produce", ({ transportId, kind, rtpParameters, source }, callback) => reply(callback, async () => { const transport = peer?.transports.get(transportId); if (!transport || transport.appData.direction !== "send" || !["mic", "camera", "screen", "screen-audio"].includes(source)) throw new Error("Invalid send request."); const producer = await transport.produce({ kind, rtpParameters, appData: { source } }); peer.producers.set(producer.id, producer); const closed = () => peer?.producers.delete(producer.id); producer.on("close", closed); producer.on("transportclose", closed); socket.to(room.id).emit("new-producer", { producerId: producer.id, userId: peer.userId, source, kind }); return { id: producer.id }; }));
  socket.on("close-producer", ({ producerId }, callback) => reply(callback, async () => { const producer = peer?.producers.get(producerId); if (producer) { producer.close(); peer.producers.delete(producerId); socket.to(room.id).emit("producer-closed", { producerId }); } return {}; }));
  socket.on("consume", ({ transportId, producerId, rtpCapabilities }, callback) => reply(callback, async () => { const transport = peer?.transports.get(transportId); if (!room || !transport || transport.appData.direction !== "recv" || !room.router.canConsume({ producerId, rtpCapabilities })) throw new Error("Cannot consume this producer."); const sourcePeer = [...room.peers.values()].find((item) => item.producers.has(producerId)); if (!sourcePeer || sourcePeer === peer) throw new Error("Producer not available."); const producer = sourcePeer.producers.get(producerId); const consumer = await transport.consume({ producerId, rtpCapabilities, paused: true, appData: { source: producer.appData.source, userId: sourcePeer.userId } }); peer.consumers.set(consumer.id, consumer); consumer.on("transportclose", () => peer?.consumers.delete(consumer.id)); consumer.on("producerclose", () => { peer?.consumers.delete(consumer.id); socket.emit("consumer-closed", { consumerId: consumer.id, producerId }); }); return { id: consumer.id, producerId, kind: consumer.kind, rtpParameters: consumer.rtpParameters, source: producer.appData.source, userId: sourcePeer.userId }; }));
  socket.on("resume-consumer", ({ consumerId }, callback) => reply(callback, async () => { const consumer = peer?.consumers.get(consumerId); if (!consumer) throw new Error("Consumer not found."); await consumer.resume(); return {}; }));
  const leave = () => { if (!room || !peer) return; socket.to(room.id).emit("peer-left", { userId: peer.userId }); closePeer(room, peer); roomManager.destroyIfEmpty(room); room = undefined; peer = undefined; }; socket.on("leave-room", (_, callback) => reply(callback, async () => { leave(); return {}; })); socket.on("disconnect", leave);
}
